require('base')
require('plugins')
require 'nvim-lastplace'.setup {}
require('color')
require('p-tree')
require('p-treesitter')
require('p-lualine')
require('p-lsp')
require('p-mason')
require('text')
require('maps')
require('telescope')
require 'colorizer'.setup()